project:
  type: website

website:
  title: "wongweiqihahaha.github.io"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: Week 9.qmd
      - href: Week 10.qmd
      - href: Week 11.qmd
      - href: Week 12.qmd
      - href: Final Project.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

